site_name: Documentation
theme:
   name: material
   logo: img/image.avif
   custom_dir: exaloop_theme
   font:
     text: Open Sans
     code: Source Code Mono
   palette:
     scheme: slate
   features:
    - content.code.copy
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/exaloop.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
plugins:
  - tags
nav:
  - Home: index.md
  - Introduction:
    - About Codon: about.md
    - Getting started: intro/intro.md
    - Frequently asked questions: intro/faq.md
    - Differences with Python: intro/differences.md
    - Release notes: intro/releases.md
    - Roadmap: intro/roadmap.md
  - Language Features:
    - Basics: language/basics.md
    - Collections: language/collections.md
    - Functions: language/functions.md
    - Classes: language/classes.md
    - Generators: language/generators.md
    - Statics: language/statics.md
    - Other types and features: language/extra.md
    - Foreign function interface: language/ffi.md
    - Inline LLVM IR: language/llvm.md
  - Interoperability:
    - NumPy support: interop/numpy.md
    - Python integration: interop/python.md
    - Python decorator: interop/decorator.md
    - Python extensions: interop/pyext.md
    - C/C++ integration: interop/cpp.md
    - Jupyter integration: interop/jupyter.md
  - Advanced:
    - Parallelism and multithreading: advanced/parallel.md
    - GPU programming: advanced/gpu.md
    - Pipelines: advanced/pipelines.md
    - Intermediate representation: advanced/ir.md
    - Building from source: advanced/build.md