name: Build Codon Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          python -m pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y pngquant

      - name: Build API reference
        run: |
          curl -L \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/exaloop/codon/actions/artifacts/3512485287/zip \
            -o artifact.zip
          unzip artifact.zip && rm artifact.zip
          tar -xvzf codon-linux-x86_64.tar.gz && rm codon-linux-x86_64.tar.gz
          codon-deploy/bin/codon doc codon-deploy/lib/codon/stdlib > docs.json
          python scripts/docgen.py docs.json docs/libraries/api $(pwd)/codon-deploy/lib/codon/stdlib

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          cname: codon.dev
